### ISSUE TITLE
Fresh install throws NullReference exception

### ISSUE THREAD

**Issue by robert-j-engdahl** [robert-j-engdahl/ngettext-wpf#7]
System.NullReferenceException
  HResult=0x80004003
  Message=Objektreferencen er ikke indstillet til en forekomst af et objekt.
  Source=NGettext.Wpf
  StackTrace:
   at NGettext.Wpf.GettextExtension.Gettext()
   at NGettext.Wpf.GettextExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   at System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at MathTraining.MainWindow.InitializeComponent() in C:\Git\MathTraining\MathTraining\MainWindow.xaml:line 1
   at MathTraining.MainWindow..ctor() in C:\Git\MathTraining\MathTraining\MainWindow.xaml.cs:line 18

**Comment by robert-j-engdahl** [comment]
#8 is probably a good solution for this.
